name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Package Info
        run:  |
          echo "::set-output name=package::$(sed -n -e 's/^Bundle-SymbolicName: //p' bnd.bnd)"
          echo "::set-output name=version::$(sed -n -e 's/^Bundle-Version: //p' bnd.bnd)"
        id: info
      - name: Install Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Liferay Blade CLI
        shell: bash
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          java -version
          git submodule update --init --recursive
          curl -L https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | sh
          echo 'export PATH="$PATH:$HOME/jpm/bin"' >> ~/.bash_profile
          source ~/.bash_profile
          blade version
          blade init -v portal-7.4-ga33 workspace
          cd workspace/modules
          modules=$(pwd)
          mkdir onlyoffice-liferay
          cd $cwd
          rsync -av --exclude='workspace' ./ ./workspace/modules/onlyoffice-liferay
          cd $modules
          blade gw jar
          cd ./onlyoffice-liferay/build/libs
          mv ${{ steps.info.outputs.package }}-${{ steps.info.outputs.version }}.jar $cwd/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.info.outputs.package }}-${{ steps.info.outputs.version }}-portal-7.4-ga33
          path: ${{ steps.info.outputs.package }}-${{ steps.info.outputs.version }}.jar
